"""add_todo_user_fk

Revision ID: 533e16fd1c44
Revises: 645dcb8d91e0
Create Date: 2026-02-12 22:15:44.749640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '533e16fd1c44'
down_revision: Union[str, Sequence[str], None] = '645dcb8d91e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('user_id', sa.Uuid(), nullable=False))
    op.create_index(op.f('ix_todo_user_id'), 'todo', ['user_id'], unique=False)
    op.create_foreign_key(None, 'todo', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'todo', type_='foreignkey')
    op.drop_index(op.f('ix_todo_user_id'), table_name='todo')
    op.drop_column('todo', 'user_id')
    # ### end Alembic commands ###
